<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.0" name="grove_base_tileset_16px" tilewidth="16" tileheight="16" tilecount="64" columns="8">
 <image source="grove_tileset.png" width="128" height="128"/>
 <tile id="0" type="grass"/>
 <tile id="1" type="path_horizontal"/>
 <tile id="2" type="path_vertical"/>
 <tile id="3" type="path_corner_tl"/>
 <tile id="4" type="path_corner_tr"/>
 <tile id="5" type="path_corner_bl"/>
 <tile id="6" type="path_corner_br"/>
 <tile id="7" type="grass_flower"/>
 <tile id="8" type="tree_base"/>
 <tile id="9" type="path_cross"/>
 <tile id="10" type="path_t_top"/>
 <tile id="11" type="path_t_bottom"/>
 <tile id="12" type="path_t_left"/>
 <tile id="13" type="path_t_right"/>
 <tile id="14" type="grass_variant"/>
 <tile id="15" type="flower_pink"/>
 <tile id="16" type="tree_top"/>
 <tile id="17" type="rock_small"/>
 <tile id="18" type="rock_medium"/>
 <tile id="19" type="rock_large"/>
 <tile id="20" type="grass_detail"/>
 <tile id="21" type="water_center"/>
 <tile id="22" type="water_edge_top"/>
 <tile id="23" type="water_edge_bottom"/>
 <tile id="24" type="bush"/>
 <tile id="25" type="water_edge_left"/>
 <tile id="26" type="water_edge_right"/>
 <tile id="27" type="water_corner_tl"/>
 <tile id="28" type="water_corner_tr"/>
 <tile id="29" type="water_corner_bl"/>
 <tile id="30" type="water_corner_br"/>
 <tile id="31" type="grass_dark"/>
 <tile id="32" type="log_horizontal"/>
 <tile id="33" type="stump"/>
 <tile id="34" type="mushroom"/>
 <tile id="35" type="bush_berry"/>
 <tile id="36" type="flower_yellow"/>
 <tile id="37" type="grass_tall"/>
 <tile id="38" type="water_animated_1"/>
 <tile id="39" type="water_animated_2"/>
 <tile id="40" type="crate"/>
 <tile id="41" type="sign"/>
 <tile id="42" type="fence_horizontal"/>
 <tile id="43" type="fence_vertical"/>
 <tile id="44" type="fence_corner"/>
 <tile id="45" type="barrel"/>
 <tile id="46" type="chest"/>
 <tile id="47" type="grass_light"/>
</tileset>